language: go
go:
- 1.16.x
addons:
  apt:
    packages:
    - rpm
env:
- GO111MODULE=on
go_import_path: github.com/uhn/ggql
install:
- go get github.com/mattn/goveralls
before_script:
- GO_LIST=$(go list ./...)
- $(exit $(go fmt $GO_LIST | wc -l))
- go vet $GO_LIST
script:
- set -e
- go test -i ./...
- go test -v -run=TestNoRace --failfast -p=1 ./...
- go test --failfast -v -race -coverprofile=./coverage.out  ./...
- if [[ "$TRAVIS_GO_VERSION" =~ 1.14 ]]; then $HOME/gopath/bin/goveralls -repotoken OYG6CaFpQcAHGtZga02zY4onchs5F5wWq -coverprofile=./coverage.out -service travis-ci; else go test -race -v -p=1 ./... --failfast; fi
- set +e
