language: go
go:
- 1.14.x
- 1.13.x
addons:
  apt:
    packages:
    - rpm
env:
- GO111MODULE=on
go_import_path: github.com/uhn/ggql
install:
before_script:
- GO_LIST=$(go list ./...)
- go build
- $(exit $(go fmt $GO_LIST | wc -l))
- go vet $GO_LIST
script:
- set -e
- go test -i ./...
- go test -v -run=TestNoRace --failfast -p=1 ./...
- if [[ "$TRAVIS_GO_VERSION" =~ 1.13 ]]; then ./scripts/cov.sh TRAVIS; else go test -v -race -p=1 --failfast ./...; fi
- set +e

deploy:
  provider: script
  cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ 1.13

